version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=bookstore
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

volumes:
  postgres_data: